# PyTorch nn.functional module stub file
from typing import Any, Optional

def softmax(input: Any, dim: int, **kwargs: Any) -> Any: ...
def log_softmax(input: Any, dim: int, **kwargs: Any) -> Any: ...
def nll_loss(input: Any, target: Any, **kwargs: Any) -> Any: ...
def relu(input: Any, **kwargs: Any) -> Any: ...
def dropout(input: Any, p: float = 0.5, training: bool = True) -> Any: ...
def linear(input: Any, weight: Any, bias: Optional[Any] = None) -> Any: ...